export const EXTENSION_NAME = 'GPT Image Generator';
export const OPENAI_API_KEY = 'OPENAI_API_KEY';
export const GEMINI_API_KEY = 'GEMINI_API_KEY';
export const CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME';
export const CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY';
export const CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET';
export const MAGIC_HOUR_API_KEY = 'MAGIC_HOUR_API_KEY';
export const DEFAULT_FREE_CREDITS = '3';
